<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>FamilyFinance</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FamilyFinance.Domain\FamilyFinance.Domain.csproj" />
    <ProjectReference Include="..\FamilyFinance.Data\FamilyFinance.Data.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlcipher" />
  </ItemGroup>
</Project>
